### ISSUE TITLE
Upgrade to jclouds 2.2.0

### ISSUE THREAD

**Issue by gaul** [bouncestorage/swiftproxy#62]
This has a few years worth of fixes compared to 2.0.0.  The tests currently fail in part due to:

```
deleteObject(com.bouncestorage.swiftproxy.JcloudsIntegrationTest)  Time elapsed: 0.027 sec  <<< FAILURE!
java.lang.IllegalArgumentException: Illegal character in path at index 18: /gaul-blobstore6/p|pe
        at java.net.URI.create(URI.java:852)
        at org.jclouds.openstack.swift.v1.config.SwiftTypeAdapters.readErrors(SwiftTypeAdapters.java:149)
        at org.jclouds.openstack.swift.v1.config.SwiftTypeAdapters$StaticLargeObjectResponseAdapter.read(SwiftTypeAdapters.java:129)
        at org.jclouds.openstack.swift.v1.config.SwiftTypeAdapters$StaticLargeObjectResponseAdapter.read(SwiftTypeAdapters.java:111)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at org.jclouds.json.internal.GsonWrapper.fromJson(GsonWrapper.java:55)
        at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:82)
        at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:76)
        at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:61)
        at org.jclouds.http.functions.ParseJson.apply(ParseJson.java:41)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at com.sun.proxy.$Proxy117.delete(Unknown Source)
        at org.jclouds.openstack.swift.v1.blobstore.RegionScopedSwiftBlobStore.removeBlob(RegionScopedSwiftBlobStore.java:398)
        at org.jclouds.blobstore.integration.internal.BaseBlobIntegrationTest.deleteObject(BaseBlobIntegrationTest.java:518)
```

@timuralp would you mind looking at this?  It may be related to some path-handling you fixed some time ago.

**Comment by timuralp** [comment]
Sure, I'll try to check it out this week.

**Comment by gaul** [comment]
Here is a branch with the changes necessary to compile:

https://github.com/gaul/swiftproxy/tree/jclouds

**Comment by gaul** [comment]
Nevermind; my master branch had some work-in-progress commits that caused these failures.
